# ==============================================================================
# Flyway Configuration: Metadata Control DB
# ==============================================================================

flyway.locations=filesystem:db/migration,filesystem:db/repeatable
flyway.schemas=INGFW
flyway.defaultSchema=INGFW
flyway.table=flyway_schema_history
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true
flyway.cleanDisabled=true
flyway.sqlMigrationSuffixes=.sql
flyway.encoding=UTF-8
