-- ==============================================================================
-- V1.1.0__CONFIG_Onboard_Eprism_Sources_And_Seed_Data.sql: Seed Configurations
-- Framework: Metadata-Driven Ingestion Engine
-- Flyway Versioned Migration: V1.1.0
-- Target Database: metadata_db (Schema: INGFW)
-- Table Prefix Standards: CONF_ (Configuration), LOG_ (Telemetry & Audit)
-- ==============================================================================

-- 1. Insert Connections
IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_CONNECTIONS WHERE CONNECTION_NAME = 'CONN_MSSQL_SOURCE')
BEGIN
    INSERT INTO INGFW.CONF_CONNECTIONS (CONNECTION_NAME, CONNECTION_TYPE, CONNECTION_PROPERTIES)
    VALUES ('CONN_MSSQL_SOURCE', 'MSSQL', '{"host": "mssql-source", "port": 1433, "database": "source_db", "user": "sa", "password": "Strong_Password_123!"}');
END;

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_CONNECTIONS WHERE CONNECTION_NAME = 'CONN_PARQUET_DEST')
BEGIN
    INSERT INTO INGFW.CONF_CONNECTIONS (CONNECTION_NAME, CONNECTION_TYPE, CONNECTION_PROPERTIES)
    VALUES ('CONN_PARQUET_DEST', 'PARQUET_LANDING', '{"base_path": "/data/parquet/bronze", "format": "parquet", "compression": "snappy"}');
END;
GO

-- 2. Insert Batch: BAT_POST_STAGING_001
DECLARE @batch_id VARCHAR(50) = 'BAT_POST_STAGING_001';
IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_BATCHES WHERE BATCH_ID = @batch_id)
BEGIN
    INSERT INTO INGFW.CONF_BATCHES (BATCH_ID, DESCRIPTION, RECOVERY_STRATEGY, MAX_TRIES, IS_ACTIVE, JOB_STAGGER_DELAY)
    VALUES (@batch_id, 'Nightly extraction of post-staging transaction tables for EPRISM solution', 'IGNORE', 1, 1, 3);
END;

DECLARE @conn_source_id INT, @conn_dest_id INT;
SELECT @conn_source_id = ID FROM INGFW.CONF_CONNECTIONS WHERE CONNECTION_NAME = 'CONN_MSSQL_SOURCE';
SELECT @conn_dest_id = ID FROM INGFW.CONF_CONNECTIONS WHERE CONNECTION_NAME = 'CONN_PARQUET_DEST';

-- 3. Job 1: J_POST_STAGING_001 (MANAGED_BILLING_HIS) - NO RETRY VERSION
DECLARE @job1_id INT, @source1_id INT;
IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_BATCH_JOBS WHERE SOLUTION_ID = 'SOL_EPRISM' AND PROJECT_ID = 'PRJ_POST_STAGING' AND JOB_ID = 'J_POST_STAGING_001')
BEGIN
    INSERT INTO INGFW.CONF_BATCH_JOBS (SOLUTION_ID, PROJECT_ID, JOB_ID, BATCH_ID, JOB_DESCRIPTION, JOB_TYPE, PREV_JOB_ID, TRANSIENT_ERROR_RETRY_COUNT, CLEANUP_ON_ERROR, IS_ACTIVE)
    VALUES ('SOL_EPRISM', 'PRJ_POST_STAGING', 'J_POST_STAGING_001', @batch_id, 'Managed billing history extraction pipeline', 'RDBMS_TO_PARQUET_NO_RETRY', NULL, 0, 1, 1);
    SET @job1_id = SCOPE_IDENTITY();

    INSERT INTO INGFW.CONF_SOURCES (JOB_ID, CONNECTION_ID, SOURCE_PROPERTIES, CHUNK_SIZE, THROTTLE_RATE)
    VALUES (@job1_id, @conn_source_id, '{"schema": "dbo", "table_name": "MANAGED_BILLING_HIS"}', 1000, 5);
    SET @source1_id = SCOPE_IDENTITY();

    INSERT INTO INGFW.CONF_DESTINATIONS (JOB_ID, CONNECTION_ID, DESTINATION_PROPERTIES, CHUNK_SIZE, BACK_PRESSURE_LIMIT)
    VALUES (@job1_id, @conn_dest_id, '{"target_dir": "/data/parquet/bronze/MANAGED_BILLING_HIS"}', 1000, 10000);

    INSERT INTO INGFW.CONF_SOURCE_KEYS (SOURCE_ID, KEY_FIELD) VALUES (@source1_id, 'id');
    INSERT INTO INGFW.CONF_WATERMARKS (SOURCE_ID, WATERMARK_STATE) VALUES (@source1_id, '{"id": 0}');
END
ELSE
BEGIN
    SELECT @job1_id = ID FROM INGFW.CONF_BATCH_JOBS WHERE SOLUTION_ID = 'SOL_EPRISM' AND PROJECT_ID = 'PRJ_POST_STAGING' AND JOB_ID = 'J_POST_STAGING_001';
END;

-- 4. Job 2: J_POST_STAGING_002 (CLOSED_BATCH_HIS) - WITH RETRY VERSION (Retry Count = 3)
DECLARE @job2_id INT, @source2_id INT;
IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_BATCH_JOBS WHERE SOLUTION_ID = 'SOL_EPRISM' AND PROJECT_ID = 'PRJ_POST_STAGING' AND JOB_ID = 'J_POST_STAGING_002')
BEGIN
    INSERT INTO INGFW.CONF_BATCH_JOBS (SOLUTION_ID, PROJECT_ID, JOB_ID, BATCH_ID, JOB_DESCRIPTION, JOB_TYPE, PREV_JOB_ID, TRANSIENT_ERROR_RETRY_COUNT, CLEANUP_ON_ERROR, IS_ACTIVE)
    VALUES ('SOL_EPRISM', 'PRJ_POST_STAGING', 'J_POST_STAGING_002', @batch_id, 'Closed batch history extraction pipeline', 'RDBMS_TO_PARQUET_WITH_RETRY', NULL, 3, 1, 1);
    SET @job2_id = SCOPE_IDENTITY();

    INSERT INTO INGFW.CONF_SOURCES (JOB_ID, CONNECTION_ID, SOURCE_PROPERTIES, CHUNK_SIZE, THROTTLE_RATE)
    VALUES (@job2_id, @conn_source_id, '{"schema": "dbo", "table_name": "CLOSED_BATCH_HIS"}', 1000, 5);
    SET @source2_id = SCOPE_IDENTITY();

    INSERT INTO INGFW.CONF_DESTINATIONS (JOB_ID, CONNECTION_ID, DESTINATION_PROPERTIES, CHUNK_SIZE, BACK_PRESSURE_LIMIT)
    VALUES (@job2_id, @conn_dest_id, '{"target_dir": "/data/parquet/bronze/CLOSED_BATCH_HIS"}', 1000, 10000);

    INSERT INTO INGFW.CONF_SOURCE_KEYS (SOURCE_ID, KEY_FIELD) VALUES (@source2_id, 'id');
    INSERT INTO INGFW.CONF_WATERMARKS (SOURCE_ID, WATERMARK_STATE) VALUES (@source2_id, '{"id": 0}');
END
ELSE
BEGIN
    SELECT @job2_id = ID FROM INGFW.CONF_BATCH_JOBS WHERE SOLUTION_ID = 'SOL_EPRISM' AND PROJECT_ID = 'PRJ_POST_STAGING' AND JOB_ID = 'J_POST_STAGING_002';
END;

-- 5. Job 3: J_POST_STAGING_004 (EPM_RULE_HISTORY) - NO RETRY VERSION
DECLARE @job3_id INT, @source3_id INT;
IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_BATCH_JOBS WHERE SOLUTION_ID = 'SOL_EPRISM' AND PROJECT_ID = 'PRJ_POST_STAGING' AND JOB_ID = 'J_POST_STAGING_004')
BEGIN
    INSERT INTO INGFW.CONF_BATCH_JOBS (SOLUTION_ID, PROJECT_ID, JOB_ID, BATCH_ID, JOB_DESCRIPTION, JOB_TYPE, PREV_JOB_ID, TRANSIENT_ERROR_RETRY_COUNT, CLEANUP_ON_ERROR, IS_ACTIVE)
    VALUES ('SOL_EPRISM', 'PRJ_POST_STAGING', 'J_POST_STAGING_004', @batch_id, 'Rule history extraction pipeline', 'RDBMS_TO_PARQUET_NO_RETRY', NULL, 0, 1, 1);
    SET @job3_id = SCOPE_IDENTITY();

    INSERT INTO INGFW.CONF_SOURCES (JOB_ID, CONNECTION_ID, SOURCE_PROPERTIES, CHUNK_SIZE, THROTTLE_RATE)
    VALUES (@job3_id, @conn_source_id, '{"schema": "dbo", "table_name": "EPM_RULE_HISTORY"}', 1000, 5);
    SET @source3_id = SCOPE_IDENTITY();

    INSERT INTO INGFW.CONF_DESTINATIONS (JOB_ID, CONNECTION_ID, DESTINATION_PROPERTIES, CHUNK_SIZE, BACK_PRESSURE_LIMIT)
    VALUES (@job3_id, @conn_dest_id, '{"target_dir": "/data/parquet/bronze/EPM_RULE_HISTORY"}', 1000, 10000);

    INSERT INTO INGFW.CONF_SOURCE_KEYS (SOURCE_ID, KEY_FIELD) VALUES (@source3_id, 'rule_id');
    INSERT INTO INGFW.CONF_WATERMARKS (SOURCE_ID, WATERMARK_STATE) VALUES (@source3_id, '{"rule_id": 0}');
END
ELSE
BEGIN
    SELECT @job3_id = ID FROM INGFW.CONF_BATCH_JOBS WHERE SOLUTION_ID = 'SOL_EPRISM' AND PROJECT_ID = 'PRJ_POST_STAGING' AND JOB_ID = 'J_POST_STAGING_004';
END;
GO

-- 6. Insert Predefined Transient Errors (Lookup Table for Automatic Retries)
IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'SOCKET_TIMEOUT')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('SOCKET_TIMEOUT', 'NETWORK_TIMEOUT', 'SocketTimeoutException', '%SocketTimeoutException%', 'Socket read/write timeout across network connection', 1);

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'CONNECT_TIMEOUT')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('CONNECT_TIMEOUT', 'NETWORK_TIMEOUT', 'ConnectTimeoutException', '%ConnectTimeoutException%', 'Initial TCP connection handshake timed out', 1);

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'CONNECTION_RESET')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('CONNECTION_RESET', 'NETWORK_TIMEOUT', 'ConnectionResetException', '%Connection reset%', 'TCP connection reset by peer/network intermediary', 1);

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'CONNECTION_REFUSED')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('CONNECTION_REFUSED', 'NETWORK_TIMEOUT', 'ConnectionRefusedException', '%Connection refused%', 'Remote database or endpoint temporarily refusing connections', 1);

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'DB_TIMEOUT')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('DB_TIMEOUT', 'NETWORK_TIMEOUT', 'TimeoutError', '%timeout%', 'General timeout communicating with source database or service', 1);

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'DEADLOCK')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('DEADLOCK', 'DATABASE_CONCURRENCY', 'DeadlockVictimException', '%Deadlock%', 'Transaction was chosen as deadlock victim on source database', 1);

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'LOCK_WAIT_TIMEOUT')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('LOCK_WAIT_TIMEOUT', 'DATABASE_CONCURRENCY', 'LockWaitTimeoutException', '%lock wait timeout%', 'Database lock acquisition request timed out', 1);

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'POOL_STARVATION')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('POOL_STARVATION', 'DATABASE_CONCURRENCY', 'SQLTransientConnectionException', '%connection pool starvation%', 'Temporary exhaustion of available JDBC connections in connection pool', 1);

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'SQL_TRANSIENT')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('SQL_TRANSIENT', 'DATABASE_CONCURRENCY', 'SQLTransientException', '%SQLTransient%', 'JDBC driver transient database exception', 1);

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'HTTP_429')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('HTTP_429', 'RATE_LIMIT_THROTTLING', 'TooManyRequestsException', '%429%', 'HTTP 429 Too Many Requests rate limit backoff', 1);

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'HTTP_503')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('HTTP_503', 'RATE_LIMIT_THROTTLING', 'ServiceUnavailableException', '%503%', 'HTTP 503 Service Unavailable upstream maintenance', 1);

IF NOT EXISTS (SELECT 1 FROM INGFW.CONF_TRANSIENT_ERRORS WHERE ERROR_CODE = 'HTTP_504')
    INSERT INTO INGFW.CONF_TRANSIENT_ERRORS (ERROR_CODE, ERROR_CATEGORY, EXCEPTION_CLASS, ERROR_PATTERN, DESCRIPTION, IS_ACTIVE)
    VALUES ('HTTP_504', 'RATE_LIMIT_THROTTLING', 'GatewayTimeoutException', '%504%', 'HTTP 504 Gateway Timeout upstream proxy timeout', 1);
GO
